Style/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: false

Style/NumericLiterals:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: true

Metrics/BlockNesting:
  Max: 2

Style/AlignHash:
  EnforcedColonStyle: 'key'
  EnforcedHashRocketStyle: 'key'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/StringLiterals:
  EnforcedStyle: double_quotes
