source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'fix-db-schema-conflicts', path: '../..'
